global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "priceservice"
    scrape_interval: 5s
    static_configs:
      - targets: ["priceservice:8080"]
